### ISSUE TITLE
Advanced Config node being ignored 

### ISSUE THREAD

**Issue by filliptm** [MinusZoneAI/ComfyUI-TrainTools-MZ#12]
I have the advanced config noded connected and dialed to my liking, but after examining the training config in the outputs folder for that run I noticed its not taking any of those settings into account, and what I'm assuming is defaulting to whatever settings are set in the back

**Comment by wailovet** [comment]
> I have the advanced config noded connected and dialed to my liking, but after examining the training config in the outputs folder for that run I noticed its not taking any of those settings into account, and what I'm assuming is defaulting to whatever settings are set in the back

What model is this happening in, SDXL/1.5? HunYuan?

**Comment by filliptm** [comment]
SD1.5

**Comment by wailovet** [comment]
> SD1.5

Try the latest version to see if this bug still exists.

**Comment by filliptm** [comment]
This fix solved it! thanks
