### ISSUE TITLE
How does captioning work? 

### ISSUE THREAD

**Issue by filliptm** [MinusZoneAI/ComfyUI-TrainTools-MZ#5]
How di i handle captioning manually? where does your nodes look for those caption text files?

**Comment by wailovet** [comment]
> How di i handle captioning manually? where does your nodes look for those caption text files?

You can manually put the image_name.caption file in output\mz_train_workspaces\xxxxx\train_images
![image](https://github.com/MinusZoneAI/ComfyUI-TrainTools-MZ/assets/5035199/dc67987a-df2a-41ba-b301-b1bfa125c3ce)

**Comment by filliptm** [comment]
I think it would make more sense for this node to pull matching txt files to the name of the images like the original Kohya, and possibly automatically move them to the workspace in the output folder?

![image](https://github.com/MinusZoneAI/ComfyUI-TrainTools-MZ/assets/55672949/4032a38e-1ca7-4b9c-9d9b-d11ad228219b)

**Comment by filliptm** [comment]
also after manually putting the captions in there it doesn't seem to recognize them either

**Comment by wailovet** [comment]
> also after manually putting the captions in there it doesn't seem to recognize them either

.caption suffix?

**Comment by filliptm** [comment]
correct, still nothing

**Comment by wailovet** [comment]
> correct, still nothing

Is it in the train_images and has the same name as the picture, and can you show me the folder by taking a screenshot, and the console information that can not be correctly recognized as captions?
